add some hint text for when the configure script fails
Ignore-this: 9eed7aaa6d9fa31e3e52dacf1d63050b

darcs-hash:20110321004639-dcabc-f1d293e670278be14da6a68d2b7d461cb58770ee.gz

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2558,6 +2558,19 @@ fi
 
 # Make sure both the driver and runtime are found
 #
+longerror='
+********************************************************************************
+
+The configuration process failed to locate your CUDA installation. Ensure that
+you have installed the driver and developer toolkit, available from:
+
+  http://developer.nvidia.com/object/cuda.html
+
+Then make sure that "nvcc" is available in your PATH, or set the appropriate
+directories with --extra-include-dirs and --extra-lib-dirs.
+
+********************************************************************************'
+
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -4014,8 +4027,8 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
 _ACEOF
 
 else
-  { { echo "$as_me:$LINENO: error: could not find CUDA headers" >&5
-echo "$as_me: error: could not find CUDA headers" >&2;}
+  { { echo "$as_me:$LINENO: error: could not find CUDA headers${longerror}" >&5
+echo "$as_me: error: could not find CUDA headers${longerror}" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -4103,8 +4116,8 @@ if test "$ac_res" != no; then
   test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
 
 else
-  { { echo "$as_me:$LINENO: error: could not find CUDA driver library" >&5
-echo "$as_me: error: could not find CUDA driver library" >&2;}
+  { { echo "$as_me:$LINENO: error: could not find CUDA driver library${longerror}" >&5
+echo "$as_me: error: could not find CUDA driver library${longerror}" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -4190,8 +4203,8 @@ if test "$ac_res" != no; then
   test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
 
 else
-  { { echo "$as_me:$LINENO: error: could not find CUDA runtime library" >&5
-echo "$as_me: error: could not find CUDA runtime library" >&2;}
+  { { echo "$as_me:$LINENO: error: could not find CUDA runtime library${longerror}" >&5
+echo "$as_me: error: could not find CUDA runtime library${longerror}" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
